name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'where_to_go/**'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'where_to_go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: where_to_go

    steps:
      - uses: actions/checkout@v5
      
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: '3.29.0'
          
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-infos